name: Release to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [published]
    
env:
  DOTNET_VERSION: '6.0.x'
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build fontawesome-wpf.csproj -c Release
    - name: Test
      run: dotnet test fontawesome-wpf.csproj -c Release --no-build
    - name: Pack nugets
      run: dotnet pack fontawesome-wpf.csproj -c Release --no-build --output .
    - name: Add NuGet source
      run: dotnet nuget add source --username DSaladinCH --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DSaladinCH/index.json"
    - name: Push to GitHub Packages
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
